### ISSUE TITLE
Changing 

### ISSUE THREAD

**Issue by rondadon** [bigbluebutton/docker#136]
Hello there!

I wanted to add/change the CameraProfiles int the settings.yml so I have an additional higher Bitrate and higher resolution WebCam Profile but none of the settings.yml Files where I changed/added the camera Profiles where represented in BigBlueButton WebUI after restarting all the containers.
So the Settings are still "stock" in the WebUI after changing the "settings.yml".

So my question would be, which config File should I modify to change and add Settings for the WebCam Settings which are shown in the WebUI when someone is activating the WebCam?

I changed following **settings.yml** Files:

**Docker-Host:**
`~/bbb-docker/mod/html5/settings.yml`

**inside html5-backend Docker-Container:**
`/app/programs/server/assets/app/config/settings.yml`

**inside html5-frontend Docker-Container:**
`/app/programs/server/assets/app/config/settings.yml`

And I added following in the "cameraProfiles:" Section to add an additional Profile:

```
      - id: hdCustom
        name: HD Custom
        default: false
        bitrate: 3000
        constraints:
          width: 1920
          frameRate: 60
```

After restarting the whole bbb Docker container stack I still don't see any changes to the offered camera Quality Settings in the DropDown menue when you want to start your WebCam stream. 

Thank you very much in advance.
