### ISSUE TITLE
use official coturn docker image

### ISSUE THREAD

**Issue by rottaran** [bigbluebutton/docker#189]
According to https://github.com/instrumentisto/coturn-docker-image the docker image is no longer maintained and https://hub.docker.com/r/coturn/coturn should be used instead. 

There also seem to be some configuration issues:
* Bad configuration format: dh2066
* You specified --lt-cred-mech and --use-auth-secret in the same time.
* Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
* socket: Protocol not supported
* configure PORT range to use. can be shared with kurento because both have host network and kernel should take care.

Many many thanks for the awesome BBB docker images! 
If nobody is working on it anyway, I can try to switch to the official coturn and create a pull reqeust. Will take a few weeks though.

**Comment by capitalfuse** [comment]
I configured like the below: section "coturn" in docker-compose.yml
```
  # coturn https://github.com/coturn/coturn/tree/master/docker
  coturn:
    image: coturn/coturn
    restart: unless-stopped
    command: ["turnserver", "--external-ip=${EXTERNAL_IPv4}/10.7.7.1", "--external-ip=${EXTERNAL_IPv6}/fe80::42:bff:fe19:2352", "--static-auth-secret=${TURN_SECRET}"]
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      #- ./mod/coturn/entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./mod/coturn/turnserver.conf:/etc/coturn/turnserver.conf
      # how to create pem file: execute "$ openssl dhparam -dsaparam  -out dhp.pem 2048"
      - ./mod/coturn/dhp.pem:/etc/turnserver/dhp.pem
    #environment:
    #  ENABLE_HTTPS_PROXY:
    network_mode: host
```
lt-cred-mech, dh2066--->comment out
