### ISSUE TITLE
Big Blue Button behind proxy

### ISSUE THREAD

**Issue by krivochenko** [bigbluebutton/docker#21]
Hi everyone!

I use https://github.com/jwilder/nginx-proxy on my server. It listens on 80 port.

I wanna use Big Blue Button and access to it by domain name bbb.my-domain.com. I need something kinda this config:

```
version: "2"

services:
  bbb:
    image: bigbluebutton/bigbluebutton
    restart: unless-stopped
    environment: 
      - VIRTUAL_HOST=bbb.my-domain.com
      - VIRTUAL_PORT=80
    ports:
      - "80:80/tcp"
      - "1935:1935"
      - "3478:3478"
      - "3478:3478/udp"
    expose:
      - 80    
    networks:
      - default
      - proxy_default  
    command: "-h bbb.my-domain.com"  # my server address
networks:
  proxy_default:
    external: true         
```

But 80 port is busy by proxy, so I have to define another one. Which extra changes I have to do?

If I specify "81:80/tcp" I see BBB running on bbb.my-domain.com, but when I follow join-link from third part app I see meeting-room and during sound-test I get 1006 error. Also in console of browser I see error: `WebSocket connection to 'wss://bbb.my-domain.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 404`

Thanks for help.
