### ISSUE TITLE
With Greenlight 3.0.2, recording processing status never updates (requires resync)

### ISSUE THREAD

**Issue by lightweight** [bigbluebutton/docker#274]
I'm running Greenlight 3.0.2 via the bigbluebutton/docker deployment (although with a manually created reverse proxy). When a recorded session finishes, Greenlight provides the "Processing recording, this may take several minutes..." message. But this message persists even through page reloads (and after the recording has been processed successfully). The only way to get a link to the processed recording to show is to 're-sync' the recordings for the room. 

According to @scouillard in https://github.com/bigbluebutton/greenlight/issues/5055 (greenlight project issue #5055), this might be due to a failure of a ping to an API endpoint on Greenlight by one of the other containers, but I'm not sure which script in which container (web? recording?) is calling the API endpoint, and why it's failing... Anyone have any insight into this?

**Comment by capitalfuse** [comment]
Docker BBB version2.6.0.6
Changed the endpoint like version 2, but keep the issue.
On my case, addition to the above issue, deskshare recordings have been blank (play continue with the white blank screen).

**Comment by capitalfuse** [comment]
### Recording processing status never updates

Resolved by added `SHARED_SECRET: ${SHARED_SECRET}` variables to **recording --> environment** section in the docker compose file.

  https://github.com/bigbluebutton/docker/issues/268

  https://github.com/ichdasich/bbb-docker/commit/a64c131e2ce05e7c16c1e9491ffebcd6d307ebc0

**Comment by lightweight** [comment]
Thanks for that @capitalfuse - I tried adding that to my docker-compose.yml in the recording -> environment section, and rebuilt the recording container, but it doesn't seem to have made any difference.

**Comment by capitalfuse** [comment]
mines like below.

`mod/recordings/bbb-web.properties`
```
bigbluebutton.web.serverURL=https://{{ .Env.DOMAIN }}
securitySalt={{ .Env.SHARED_SECRET }}
```

`docker-compose.yml`
```
  # recordings
  recordings:
    build: 
      context: mod/recordings
      args:
        BBB_BUILD_TAG: v2022-12-29-grails-524
        TAG_RECORDINGS: v2.6.0
        TAG_BBB_PRESENTATION_VIDEO: 4.0.0-rc.2
    image: alangecker/bbb-docker-recordings:v2.6.0
    restart: unless-stopped
    depends_on:
      - redis
      - bbb-pads
    environment:
      DOMAIN: ${DOMAIN}
      SHARED_SECRET: ${SHARED_SECRET}
    volumes:
      - bigbluebutton:/var/bigbluebutton
      - vol-freeswitch:/var/freeswitch/meetings
      - vol-mediasoup:/var/mediasoup
      - vol-kurento:/var/kurento
    tmpfs:
      - /var/log/bigbluebutton
      - /tmp
    networks:
      bbb-net:
        ipv4_address: 10.7.7.16
```
