### ISSUE TITLE
Greenlight UI behind Nginx Reverse Proxy

### ISSUE THREAD

**Issue by alex-u-93** [bigbluebutton/docker#359]
Hello,

I am setting up BBB on my own VPS with my domain.

Currently I am trying to get SSL encryption of Greenlight web UI via acquired by Certbot SSL certificate.

As I understand, the question is to setup haproxy, bundled in your docker compose, properly.

Question list

1. if on phase of config generation, disabled HTTPS also disable HTTP traffic?
2. is it possible to make it acquire SSL certificate via your setup script, is it possible to manually change docker compose config and leave only `80` port open?
3. TLS certificate (lets encrypt) is necessary not only for HTTPS?

General problem is proxying all my HTTP 1.1 traffic behind nginx proxy server that upgrades to http 2 protocol with encryption.

I am currently got certificate  by installation script, and change docker compose haproxy config to

```yaml
haproxy:                                                                      
    build: mod/haproxy                                                          
    image: alangecker/bbb-haproxy:2.8.10                                        
    volumes:                                                                    
      - ./mod/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg                      
      - ./mod/haproxy/protocolmap:/etc/haproxy/protocolmap                      
    environment:                                                                
      - IGNORE_TLS_CERT_ERRORS=true                                             
    ports:                                                                      
      - 8888:80
```

but I got an error in web browser

```

The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

```
