### ISSUE TITLE
Problem for working on local zone

### ISSUE THREAD

**Issue by arynishere** [bigbluebutton/docker#361]
We have an internal server at the company with a local IP of 172.16.x.x. We exposed this server through the firewall to a public IP, and I set this public IP to `bbb` in the `.env` file, but it's not working. Why?

**Comment by ben-ba** [comment]
so u can't use letsencrypt directly on this server?

if yes:

1. create certs
2. update your haproxy/bootstrap.sh, so you can use your certs

gerneral:

u have to access your server by fqdn

please be specific with you issue

e.g. can you reach the haproxy/nginx?, all containers running? sth in the logs? (docker compose logs -f

**Comment by LeYom** [comment]
Hi,

To solve this, I followed what @ben-ba described.

1. Edit the file docker-compose.yml 
```yml
  haproxy:
    build: mod/haproxy
    image: alangecker/bbb-haproxy:2.8.10
    volumes:
      - /path/to/mydomaincert/fullchain.pem:/etc/haproxy/certs/haproxy-10.7.7.1.pem
      - /path/to/mydomaincert/privkey.pem:/etc/haproxy/certs/haproxy-10.7.7.1.pem.key
      - ./mod/haproxy/bootstrap.sh:/bootstrap.sh
      …
```

2. Edit the file mod/haproxy/bootstrap.sh like this (ommitting the call to letsencrypt API)

```bash
#!/usr/bin/env bash

set -e

# save container environment variables to use it
# in cron scripts

declare -p | grep -Ev '^declare -[[:alpha:]]*r' > /container.env

# go!
supervisord -c /etc/supervisord.conf -n
```
