### ISSUE TITLE
get API URL and key

### ISSUE THREAD

**Issue by mokkin** [bigbluebutton/docker#84]
I'd like to connect BBB to Nextcloud via https://github.com/sualko/cloud_bbb

Is there a way to get the URL and secret via `bb-conf --secret` as described even in the docker environment?

**Comment by alangecker** [comment]
the URL is always `https://yourdomain.org/bigbluebutton/api` and the secret/key is stored as `SHARED_SECRET` inside the `.env` file ;)

**Comment by mokkin** [comment]
I supposed the `SHARED_SECRET` could be the key, but with the URLs I am not lucky :(

I tried
`https://bbb.example.de/bigbluebutton/api`
`https://bbb.example.de/api`
`https://bbb.example.de/b/bigbluebutton/api`
`https://bbb.example.de/b/api`
but the answer is always:
![grafik](https://user-images.githubusercontent.com/2938748/113941740-f81c7000-97ff-11eb-8c0b-25dab64b3c70.png)

**Comment by qroac** [comment]
I had the same riddle.  
According to (https://github.com/sualko/cloud_bbb/)[docs of the NC integration], I tried `https://bbb.mydoma.in/bigbluebutton`, without trailing api, and it works :)

**Comment by mokkin** [comment]
Now with 2.3 the NC integration is working - at least for us.
If @qroac can acknowledge this, we can close the issue.

**Comment by qroac** [comment]
Using the url path without trailing `/api/` already worked on my server at the time of my comment ;)

**Comment by ZelphirKaltstahl** [comment]
What is not clear to me is: How do I get the `BIGBLUEBUTTON_SECRET` mentioned at <https://docs.bigbluebutton.org/greenlight/gl-install.html#setting-bigbluebutton-credentials> of my own setup? Is it the same as `SHARED_SECRET` in the `.env` file then?

> the URL is always `https://yourdomain.org/bigbluebutton/api` and the secret/key is stored as `SHARED_SECRET` inside the `.env` file ;)

This makes it sound like they are the same.

**Comment by rottaran** [comment]
@ZelphirKaltstahl: This may not be caused by the shared key. I get this error message when the greenlight container cannot connect to the respective bbb container. greenlight needs to access https://mysubdomain.mydomain.com/bigbluebutton. Without extra settings, this is translated to your public IP address, but the docker container cannot connect to that. 

Solution depends on how you set up your http frontend. bbb-docker's template has the nginx frontend as network:host. I am not sure why this is sufficient. If your nginx frontend is just a container with the usual port binding for 80 and 443 the following setup will work. 172.17.0.1 is docker's host-gateway and yes it is fine to bind ports to that.

```
services:
  frontend:
    build: nginx # or something elso
    ports:
      # expose to outside
      - $(EXTERNAL_IP):80:80
      - $(EXTERNAL_IP):443:443
      # make accessible to other docker containers, likely there is a better way
      - 172.17.0.1:80:80
      - 172.17.0.1:443:443
   # ...and other settings
```

and to all bbb-docker services I have added a /etc/hosts entry. This translates your public server name to the internal IP address:
```
    extra_hosts:
      - ${DOMAIN}:host-gateway
```

Maybe there is a more elegant solution.
