### ISSUE TITLE
Disable apps-akka and jodconverter possible ?

### ISSUE THREAD

**Issue by chfxr** [bigbluebutton/docker#96]
Hello,
it is possible to disable apps-akka and the jodconverter when the whiteboard and the presentation upload will not be used ?

**Comment by chfxr** [comment]
Solution:
```
{{ if isTrue .Env.ENABLE_DOCUMENT_CONVERTER}}
  jodconverter:
    build: mod/jodconverter
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      bbb-net:
        ipv4_address: 10.7.0.20
  {{end}}

# Disabled because its not needed, restart will be done externally
{{ if isTrue .Env.ENABLE_PERIODIC }}
  periodic:
    build: mod/periodic
    restart: unless-stopped
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bigbluebutton:/var/bigbluebutton
    networks:
      bbb-net:
        ipv4_address: 10.7.0.12
{{end}}
```
